travis:
  secure:
    BINSTAR_TOKEN: auKPdjqfNeLeTKPYqbMPHtYX+EKlmudL5uD9X6H3xopGcvtqv3kiIIRbGgH3OEuwa+OuXSWu+/O6GMS+qpFFJu9iU0tokxIkmfwrQxPUklNUo7QuJap9XbyhfmTtHnoJ7/bWubxOAZ2Z0mRQx0/kh+AjUOKao+l1Lef+aIIFf1+b64Lqwy51jC+cZxG2FgRjK+9g0TEs6vz1DRWWB6G++XiVGVoLnf4Jac2zeQCA7VLvvKyQ0WX9UHwSos5sWT3zGnN+aQodpbvk02IpGIKFbcPTmX4nprHQ2iEOQi+26LVgzR+ipuyNIcH5Lxr5s+t58uc3B5JLurj0K+wGm3+nhs73HMtCQQCMQw2imowXFP9v1px57RebMJ2H3McpRkfcEo+nLHvUxm8TQN34g0WdHlfBjAE+HT8WbjCpdgItIVpt0kwTtTWVEb38fLURrNgkAYsuLhwJjHsvCrg0NBjijEkNga5XuJ9Z7jgC922UcRiHqEhMjU4rhXz48j4Eg6kIKQ7LVXypgqzi2rwsMOPfLdzy4fYWHQliswrcvGFd6y0JUoGDwFjLtg2qkuihaW0fng5LL1I6z8l1s9B4seIzxE1tV8Eq2RpylQOwU6TgOeZwt0XYwi+DsYdLdQRxJCI+KhaTMSWiEDAipkKUExs+WQ5ZcwWz1j0WFqtsuXuSoCw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
